### ISSUE TITLE
挂载手机设备失败

### ISSUE THREAD

**Issue by yanqian** [openatx/atx-server#18]
1. connect phone to Mac，uninstall uiautomator
![image](https://user-images.githubusercontent.com/2221926/40419913-47f566fa-5eb9-11e8-81cc-c8b9dfbe3bc6.png)
2. start rethinkdb
![image](https://user-images.githubusercontent.com/2221926/40419976-7765b78c-5eb9-11e8-9af0-f4237ccfdb9a.png)
3. start atx-server
![image](https://user-images.githubusercontent.com/2221926/40420028-9bcef9e4-5eb9-11e8-9c9e-776d0772318b.png)
4. go to localhost:8000, no device connected
![image](https://user-images.githubusercontent.com/2221926/40420078-c3bbb960-5eb9-11e8-99b4-f9eb6dd559ab.png)

5. init atx-agent successfully(uiautomator2 already installed)
![image](https://user-images.githubusercontent.com/2221926/40420136-e9c294f8-5eb9-11e8-9b5e-c0250ebe3d06.png)

6. refresh localhost:8000, still no device connected.
![image](https://user-images.githubusercontent.com/2221926/40420207-30c30310-5eba-11e8-9844-22252aa62548.png)

7. rethinkdb console:
![image](https://user-images.githubusercontent.com/2221926/40420227-4c7f39ca-5eba-11e8-88b5-a887ac071bb5.png)

Note：
Phone IP: 10.2.200.89
Mac IP: 10.2.200.84
Phone： Samsung Galaxy A5
Android Version： 6.0.1

atx-agent log:
```
2018/05/24 08:01:12 main.go:1287: Ignore SIGHUP
2018/05/24 08:01:12 main.go:1291: Kill server
2018/05/24 08:01:12 main.go:1294: wait previous server stopped
atx-agent version 0.3.2
Listen on http://10.2.200.156:7912
2018/05/24 08:01:15 cmdctrl.go:27: DEBUG start args: [am instrument -w -r -e debug false -e class com.github.uiautomator.stub.Stub com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner], env: []
2018/05/24 08:01:15 cmdctrl.go:27: DEBUG program pid: 9146
2018/05/24 08:01:15 main.go:745: rotation change received: 0
2018/05/24 08:01:15 cmdctrl.go:27: DEBUG cmd args: [/data/local/tmp/minicap -S -P 720x1280@800x800/0]2018/05/24 08:01:16 main.go:745: rotation change received: 0
2018/05/24 08:01:16 cmdctrl.go:27: DEBUG cmd args: [/data/local/tmp/minicap -S -P 720x1280@800x800/0]
INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.github.uiautomator.stub.Stub:
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: test=testUIAutomatorStub
INSTRUMENTATION_STATUS: class=com.github.uiautomator.stub.Stub
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS_CODE: 1
2018/05/24 08:01:21 heartbeat.go:171: heatbeat err: post form: Post http://10.2.200.84:8000/heartbeat: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers), retry after 14s
2018/05/24 08:01:40 heartbeat.go:171: heatbeat err: post form: Post http://10.2.200.84:8000/heartbeat: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers), retry after 13s
2018/05/24 08:01:58 heartbeat.go:171: heatbeat err: post form: Post http://10.2.200.84:8000/heartbeat: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers), retry after 12s
2018/05/24 08:02:15 heartbeat.go:171: heatbeat err: post form: Post http://10.2.200.84:8000/heartbeat: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers), retry after 13s
2018/05/24 08:02:33 heartbeat.go:171: heatbeat err: post form: Post http://10.2.200.84:8000/heartbeat: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers), retry after 12s
2018/05/24 08:02:50 heartbeat.go:171: heatbeat err: post form: Post http://10.2.200.84:8000/heartbeat: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers), retry after 10s
2018/05/24 08:03:05 heartbeat.go:171: heatbeat err: post form: Post http://10.2.200.84:8000/heartbeat: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers), retry after 11s
2018/05/24 08:03:21 heartbeat.go:171: heatbeat err: post form: Post http://10.2.200.84:8000/heartbeat: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers), retry after 13s
```

**Comment by codeskyblue** [comment]
试试更新 atx-server带代码，重新编译下

**Comment by yanqian** [comment]
@codeskyblue 代码更新了，也重新试了。但是还是不行。
atx-server和heartbeat的代码看起来好像没有更新。

**Comment by codeskyblue** [comment]
看看是不是网络的问题，能不能ping通。

**Comment by yanqian** [comment]
@codeskyblue  我现在可以复现问题了。

atx-server在`db.DeviceUpdate(info)` [link](https://github.com/openatx/atx-server/blob/a14e50ea627cf0ab75c29ad67ec5ec9c12bfbba1/httpserver.go#L254)这个方法里面，当遇到 DeviceInfo的`product_id`字段为空，就会更新出错。
我用requests可以复现atx-agent 请求atx-server时的错误信息，因为二者的DeviceInfo的数据一致。

atx-server端接收 DeviceInfo的`product_id`字段为空时的log（通过requests请求）:
```
proto.DeviceInfo{Udid:"F6DIMR5LZDUSNRSC-e4:47:90:4c:8c:fe-A1601", PropertyId:"", Version:"6.1", Serial:"F6DIMR5LZDUSNRSC", Brand:"OPPO", Model:"A1601", HWAddr:"e4:47:90:4c:8c:fe", IP:"", Port:0, ReverseProxyAddr:"", ReverseProxyServerAddr:"", Sdk:22, AgentVersion:"dev", Display:(*androidutils.Display)(0xc4202de190), Battery:(*androidutils.Battery)(0xc4201b74f0), Memory:(*proto.MemoryInfo)(0xc4202dc2a0), Cpu:(*proto.CpuInfo)(0xc4202dc2c0), ConnectionCount:0, Reserved:"", CreatedAt:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, PresenceChangedAt:time.Time{wall:0x0, ext:63587343845, loc:(*time.Location)(nil)}, UsingBeganAt:time.Time{wall:0x0, ext:63587343845, loc:(*time.Location)(nil)}, Ready:(*bool)(0xc4202de1be), Present:(*bool)(0xc4202de169), Using:(*bool)(0xc4202de168), Product:(*proto.Product)(nil)}2018/05/25 18:58:28 http: panic serving 10.2.200.84:63498: runtime error: invalid memory address or nil pointer dereference
goroutine 12 [running]:
net/http.(*conn).serve.func1(0xc420247400)
	/usr/local/opt/go/libexec/src/net/http/server.go:1726 +0xd0
panic(0x14717c0, 0x17b8c30)
	/usr/local/opt/go/libexec/src/runtime/panic.go:502 +0x229
main.newHandler.func14(0x155b1c0, 0xc4201e2210, 0xc420242d00)
	/Users/yanq/go/src/github.com/openatx/atx-server/httpserver.go:264 +0x4b8
net/http.HandlerFunc.ServeHTTP(0x151d080, 0x155b1c0, 0xc4201e2210, 0xc420242d00)
	/usr/local/opt/go/libexec/src/net/http/server.go:1947 +0x44
github.com/openatx/atx-server/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420084c00, 0x155b1c0, 0xc4201e2210, 0xc420242d00)
	/Users/yanq/go/src/github.com/openatx/atx-server/vendor/github.com/gorilla/mux/mux.go:133 +0xed
github.com/openatx/atx-server/vendor/github.com/mash/go-accesslog.(*LoggingHandler).ServeHTTP(0xc420252150, 0x155b500, 0xc4201ae620, 0xc420242b00)
	/Users/yanq/go/src/github.com/openatx/atx-server/vendor/github.com/mash/go-accesslog/accesslog.go:137 +0x442
net/http.serverHandler.ServeHTTP(0xc4201a4750, 0x155b500, 0xc4201ae620, 0xc420242b00)
	/usr/local/opt/go/libexec/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc420247400, 0x155ba00, 0xc42002ec40)
	/usr/local/opt/go/libexec/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/usr/local/opt/go/libexec/src/net/http/server.go:2795 +0x27b

```



init过程中，atx-agent请求atx-server时，atx-agent的log:
```
2018/05/25 11:04:58 main.go:1292: Ignore SIGHUP
  2 2018/05/25 11:04:58 main.go:1296: Kill server
  3 2018/05/25 11:04:58 main.go:1299: wait previous server stopped
  4 atx-agent version dev
  5 Listen on http://10.2.200.156:7912
  6 2018/05/25 11:05:01 main.go:1359: ------------------------------
  7 2018/05/25 11:05:01 main.go:1360: Do I come here before heartbeat?
  8 2018/05/25 11:05:01 main.go:1361: ------------------------------
  9 2018/05/25 11:05:01 main.go:1363: ------------------------------
 10 2018/05/25 11:05:01 main.go:1364: Do I come here after heartbeat?
 11 2018/05/25 11:05:01 main.go:1365: ------------------------------
 12 2018/05/25 11:05:01 cmdctrl.go:27: DEBUG start args: [am instrument -w -r -e debug false -e class c    om.github.uiautomator.stub.Stub com.github.uiautomator.test/android.support.test.runner.AndroidJUni    tRunner], env: []
 13 2018/05/25 11:05:01 tunnelproxy.go:83: F6DIMR5LZDUSNRSC-e4:47:90:4c:8c:fe-A1601
 14 2018/05/25 11:05:01 tunnelproxy.go:84: http://10.2.200.84:8000/heartbeat
 15 2018/05/25 11:05:01 tunnelproxy.go:85: 10.2.200.84:8000
 16 2018/05/25 11:05:01 tunnelproxy.go:86: F6DIMR5LZDUSNRSC-e4:47:90:4c:8c:fe-A1601
 17 2018/05/25 11:05:01 cmdctrl.go:27: DEBUG program pid: 5487
 18 INSTRUMENTATION_STATUS: numtests=1
 19 INSTRUMENTATION_STATUS: stream=
 20 com.github.uiautomator.stub.Stub:
 21 INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
 22 INSTRUMENTATION_STATUS: test=testUIAutomatorStub
 23 INSTRUMENTATION_STATUS: class=com.github.uiautomator.stub.Stub
 24 INSTRUMENTATION_STATUS: current=1
 25 INSTRUMENTATION_STATUS_CODE: 1
 26 2018/05/25 11:05:03 main.go:759: rotation change received: 0
27 2018/05/25 11:05:03 cmdctrl.go:27: DEBUG cmd args: [/data/local/tmp/minicap -S -P 720x1280@800x800/    0]
 28 2018/05/25 11:05:03 tunnelproxy.go:141: device info -------------------
 29 &proto.DeviceInfo{Udid:"F6DIMR5LZDUSNRSC-e4:47:90:4c:8c:fe-A1601", PropertyId:"", Version:"5.1", Se    rial:"F6DIMR5LZDUSNRSC", Brand:"OPPO", Model:"A1601", HWAddr:"e4:47:90:4c:8c:fe", IP:"", Port:0, Re    verseProxyAddr:"", ReverseProxyServerAddr:"", Sdk:22, AgentVersion:"dev", Display:(*androidutils.Di    splay)(0x1131ab58), Battery:(*androidutils.Battery)(0x1136e990), Memory:(*proto.MemoryInfo)(0x113af    740), Cpu:(*proto.CpuInfo)(0x113af770), ConnectionCount:0, Reserved:"", CreatedAt:time.Time{wall:0x    0, ext:0, loc:(*time.Location)(nil)}, PresenceChangedAt:time.Time{wall:0x0, ext:0, loc:(*time.Locat    ion)(nil)}, UsingBeganAt:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, Ready:(*bool)(nil),     Present:(*bool)(nil), Using:(*bool)(nil), Product:(*proto.Product)(nil)}2018/05/25 11:05:03 tunnel    proxy.go:141: device info -------------------
30  &proto.DeviceInfo{Udid:"F6DIMR5LZDUSNRSC-e4:47:90:4c:8c:fe-A1601", PropertyId:"", Version:"5.1", Se    rial:"F6DIMR5LZDUSNRSC", Brand:"OPPO", Model:"A1601", HWAddr:"e4:47:90:4c:8c:fe", IP:"", Port:0, Re    verseProxyAddr:"", ReverseProxyServerAddr:"", Sdk:22, AgentVersion:"dev", Display:(*androidutils.Di    splay)(0x1131ab58), Battery:(*androidutils.Battery)(0x1136e990), Memory:(*proto.MemoryInfo)(0x113af    740), Cpu:(*proto.CpuInfo)(0x113af770), ConnectionCount:0, Reserved:"", CreatedAt:time.Time{wall:0x    0, ext:0, loc:(*time.Location)(nil)}, PresenceChangedAt:time.Time{wall:0x0, ext:0, loc:(*time.Locat    ion)(nil)}, UsingBeganAt:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, Ready:(*bool)(nil),     Present:(*bool)(nil), Using:(*bool)(nil), Product:(*proto.Product)(nil)}2018/05/25 11:05:03 tunnel    proxy.go:141: device info -------------------
31 &proto.DeviceInfo{Udid:"F6DIMR5LZDUSNRSC-e4:47:90:4c:8c:fe-A1601", PropertyId:"", Version:"5.1", Se    rial:"F6DIMR5LZDUSNRSC", Brand:"OPPO", Model:"A1601", HWAddr:"e4:47:90:4c:8c:fe", IP:"", Port:0, Re    verseProxyAddr:"", ReverseProxyServerAddr:"", Sdk:22, AgentVersion:"dev", Display:(*androidutils.Di    splay)(0x1131ab58), Battery:(*androidutils.Battery)(0x1136e990), Memory:(*proto.MemoryInfo)(0x113af    740), Cpu:(*proto.CpuInfo)(0x113af770), ConnectionCount:0, Reserved:"", CreatedAt:time.Time{wall:0x    0, ext:0, loc:(*time.Location)(nil)}, PresenceChangedAt:time.Time{wall:0x0, ext:0, loc:(*time.Locat    ion)(nil)}, UsingBeganAt:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}, Ready:(*bool)(nil),     Present:(*bool)(nil), Using:(*bool)(nil), Product:(*proto.Product)(nil)}2018/05/25 11:05:07 heartb    eat.go:171: heatbeat err: post form: Post http://10.2.200.84:8000/heartbeat: net/http: request canc    eled while waiting for connection (Client.Timeout exceeded while awaiting headers), retry after 11s
 32 2018/05/25 11:05:08 tunnelproxy.go:151: res err -------------------
 33 <nil> Post http://10.2.200.84:8000/devices/F6DIMR5LZDUSNRSC-e4:47:90:4c:8c:fe-A1601/info: net/http:     request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
 34 2018/05/25 11:05:08 tunnelproxy.go:151: res err -------------------
 35 <nil> Post http://10.2.200.84:8000/devices/F6DIMR5LZDUSNRSC-e4:47:90:4c:8c:fe-A1601/info: net/http:     request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
 36 2018/05/25 11:05:08 tunnelproxy.go:151: res err -------------------
 37 <nil> Post http://10.2.200.84:8000/devices/F6DIMR5LZDUSNRSC-e4:47:90:4c:8c:fe-A1601/info: net/http:     request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
init过程中，atx-agent请求atx-server时，atx-server的log为空。

**Comment by yanqian** [comment]
And this is the request script.

```
url = "http://10.2.200.84:8000/devices/F6DIMR5LZDUSNRSC-e4:47:90:4c:8c:fe-A1601/info"
device_info = {
			'AgentVersion': 'dev',
			'Battery': {},
			'Brand': 'OPPO',
			'ConnectionCount': 0,
			'Cpu': {'Cores': 4, 'Hardware': 'Quan'},
			'CreatedAt': '2016-01-02T15:04:05Z',
			'Display': {'Height': 1280, 'Width': 480},
			'HWAddr': 'e4:47:90:4c:8c:fe',
			'IP': '',
			'Memory': {'Around': '4G', 'Total': 4194304},
			'Model': 'A1601',
			'Port': 0,
			'PresenceChangedAt': '2016-01-02T15:04:05Z',
			'Present': False,
			# 'Product': {},
			'product_id':'',
			'PropertyId': '',
			'Ready': True,
			'Reserved': '',
			'ReverseProxyAddr': '',
			'ReverseProxyServerAddr': '',
			'Sdk': 22,
			'Serial': 'F6DIMR5LZDUSNRSC',
			'Udid': 'F6DIMR5LZDUSNRSC-e4:47:90:4c:8c:fe-A1601',
			'Using': False,
			'UsingBeganAt': '2016-01-02T15:04:05Z',
			'Version': '6.1'
}
r = requests.post(url, data=json.dumps(device_info))
print(r.status_code)
print(r.text)
```

**Comment by yanqian** [comment]
solved by closing my own proxy software installed by company.
