### ISSUE TITLE
设备第一次连接时web页面信息显示不全

### ISSUE THREAD

**Issue by numbqq** [openatx/atx-server#35]
设备第一次连接时web页面显示信息不全，如只会显示IP，其他信息如Serial，版本号等都没有显示，如下图：
![image](https://dl.khadas.com/Docs/111.png)

我使用如下API测试发现Serial，版本号等信息也是没有的
```
curl 192.168.1.230:8000/list
```

必须把设备重启一次后才会显示完整信息，请问你那边有这种现象吗？

**Comment by mingyuan-xia** [comment]
设备上的atxagent.log贴一下

**Comment by numbqq** [comment]
Hello @mingyuan-xia 

Log 如下：
```
2018/12/28 03:46:46 main.go:1378: Ignore SIGHUP
2018/12/28 03:46:46 main.go:1382: Kill server
2018/12/28 03:46:46 main.go:1388: Get http://127.0.0.1:7912/stop: dial tcp 127.0.0.1:7912: connect: connection refused
atx-agent version dev
Listen on http://192.168.1.115:7912
2018/12/28 03:46:47 cmdctrl.go:27: DEBUG start args: [am instrument -w -r -e debug false -e class com.github.uiautomator.stub.Stub com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner], env: []
2018/12/28 03:46:47 cmdctrl.go:27: DEBUG program pid: 2259
2018/12/28 03:46:47 tunnelproxy.go:124: dev version, skip version upgrade
onError: commandError=true message=INSTRUMENTATION_FAILED: com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner
android.util.AndroidException: INSTRUMENTATION_FAILED: com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner
	at com.android.commands.am.Instrument.run(Instrument.java:421)
	at com.android.commands.am.Am.runInstrument(Am.java:187)
	at com.android.commands.am.Am.onRun(Am.java:80)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
	at com.android.commands.am.Am.main(Am.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner}
INSTRUMENTATION_STATUS: id=ActivityManagerService
INSTRUMENTATION_STATUS_CODE: -1
2018/12/28 03:46:48 cmdctrl.go:27: DEBUG cmd wait err: exit status 1
2018/12/28 03:46:48 cmdctrl.go:27: DEBUG idle for 500ms
2018/12/28 03:46:49 cmdctrl.go:27: DEBUG start args: [am instrument -w -r -e debug false -e class com.github.uiautomator.stub.Stub com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner], env: []
2018/12/28 03:46:49 cmdctrl.go:27: DEBUG program pid: 2339
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner}
onError: commandError=true message=INSTRUMENTATION_FAILED: com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner
INSTRUMENTATION_STATUS: id=ActivityManagerService
INSTRUMENTATION_STATUS_CODE: -1
android.util.AndroidException: INSTRUMENTATION_FAILED: com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner
	at com.android.commands.am.Instrument.run(Instrument.java:421)
	at com.android.commands.am.Am.runInstrument(Am.java:187)
	at com.android.commands.am.Am.onRun(Am.java:80)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
	at com.android.commands.am.Am.main(Am.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)
2018/12/28 03:46:50 cmdctrl.go:27: DEBUG cmd wait err: exit status 1
2018/12/28 03:46:50 cmdctrl.go:27: DEBUG idle for 500ms
2018/12/28 03:46:50 cmdctrl.go:27: DEBUG start args: [am instrument -w -r -e debug false -e class com.github.uiautomator.stub.Stub com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner], env: []
2018/12/28 03:46:50 cmdctrl.go:27: DEBUG program pid: 2444
onError: commandError=true message=INSTRUMENTATION_FAILED: com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner
android.util.AndroidException: INSTRUMENTATION_FAILED: com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner
	at com.android.commands.am.Instrument.run(Instrument.java:421)
	at com.android.commands.am.Am.runInstrument(Am.java:187)
	at com.android.commands.am.Am.onRun(Am.java:80)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
	at com.android.commands.am.Am.main(Am.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner}
INSTRUMENTATION_STATUS: id=ActivityManagerService
INSTRUMENTATION_STATUS_CODE: -1
2018/12/28 03:46:51 cmdctrl.go:27: DEBUG cmd wait err: exit status 1
2018/12/28 03:46:51 cmdctrl.go:27: DEBUG idle for 500ms
2018/12/28 03:46:52 cmdctrl.go:27: DEBUG start args: [am instrument -w -r -e debug false -e class com.github.uiautomator.stub.Stub com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner], env: []
2018/12/28 03:46:52 cmdctrl.go:27: DEBUG program pid: 2495
onError: commandError=true message=INSTRUMENTATION_FAILED: com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner
INSTRUMENTATION_STATUS: Error=Unable to find instrumentation info for: ComponentInfo{com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunner}
android.util.AndroidException: INSTRUMENTATION_FAILED: com.github.uiautomator.test/android.support.test.runner.AndroidJUnitRunnerINSTRUMENTATION_STATUS: id=ActivityManagerService

INSTRUMENTATION_STATUS_CODE: -1
	at com.android.commands.am.Instrument.run(Instrument.java:421)
	at com.android.commands.am.Am.runInstrument(Am.java:187)
	at com.android.commands.am.Am.onRun(Am.java:80)
	at com.android.internal.os.BaseCommand.run(BaseCommand.java:54)
	at com.android.commands.am.Am.main(Am.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:285)
2018/12/28 03:46:53 cmdctrl.go:27: DEBUG cmd wait err: exit status 1
2018/12/28 03:46:53 cmdctrl.go:27: DEBUG idle for 500ms
2018/12/28 03:46:53 cmdctrl.go:27: DEBUG program finished
2018/12/28 03:47:07 main.go:1005: minitouch connection: 192.168.1.230:46454
2018/12/28 03:47:07 cmdctrl.go:27: DEBUG start args: [/data/local/tmp/minitouch], env: []
2018/12/28 03:47:07 main.go:1024: dial @minitouch error: dial unix @minitouch: connect: connection refused, wait 0.5s
2018/12/28 03:47:07 cmdctrl.go:27: DEBUG program pid: 2698
2018/12/28 03:47:07 main.go:1085: minicap connection: 192.168.1.230:46456
2018/12/28 03:47:07 cmdctrl.go:27: DEBUG start args: [/data/local/tmp/minicap -S -P 1088x1920@800x800/0 -Q 80], env: [LD_LIBRARY_PATH=/data/local/tmp]
2018/12/28 03:47:07 main.go:1101: dial @minicap err: dial unix @minicap: connect: connection refused, wait 0.5s
2018/12/28 03:47:07 cmdctrl.go:27: DEBUG program pid: 2699
2018/12/28 03:47:07 main.go:1032: unix @minitouch connected, accepting requests
```

**Comment by mingyuan-xia** [comment]
有两个apk是否都装了，一个是uiautomator.apk 另一个是 uiautomator-test.apk

**Comment by numbqq** [comment]
你好 @mingyuan-xia，

`uiautomator.apk `这个APK是装了的，这个没有装`uiautomator-test.apk`，这个是一定要装的吗？

**Comment by mingyuan-xia** [comment]
是的，两个是配套使用的， `python -m uiautomator init` 应该是两个都会自动装，如果要手工装，参考：
https://github.com/openatx/uiautomator2/wiki/Manual-Init
