### ISSUE TITLE
init 失败

### ISSUE THREAD

**Issue by Duchongc** [openatx/atx-server#36]
ialing ...
2018-12-14 16:17:39,775 - __main__.py:133 - INFO - install minicap
2018-12-14 16:17:39,994 - __main__.py:140 - INFO - install minitouch
2018-12-14 16:17:40,428 - __main__.py:168 - INFO - apk(1.1.7) already installed,
 skip
2018-12-14 16:17:40,429 - __main__.py:350 - INFO - atx-agent is already running,
 force stop
2018-12-14 16:17:41,041 - __main__.py:227 - INFO - atx-agent(0.5.1) is installin
g, please be patient
Traceback (most recent call last):
  File "C:\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\lib\site-packages\uiautomator2\__main__.py", line 424, in <m
odule>
    main()
  File "C:\Python37\lib\site-packages\uiautomator2\__main__.py", line 420, in ma
in
    fire.Fire(MyFire)
  File "C:\Python37\lib\site-packages\fire\core.py", line 127, in Fire
    component_trace = _Fire(component, args, context, name)
  File "C:\Python37\lib\site-packages\fire\core.py", line 366, in _Fire
    component, remaining_args)
  File "C:\Python37\lib\site-packages\fire\core.py", line 542, in _CallCallable
    result = fn(*varargs, **kwargs)
  File "C:\Python37\lib\site-packages\uiautomator2\__main__.py", line 331, in in
it
    ignore_apk_check)
  File "C:\Python37\lib\site-packages\uiautomator2\__main__.py", line 356, in _i
nit_with_serial
    ins.install_atx_agent(agent_version, reinstall)
  File "C:\Python37\lib\site-packages\uiautomator2\__main__.py", line 242, in in
stall_atx_agent
    path = cache_download(url)
  File "C:\Python37\lib\site-packages\uiautomator2\__main__.py", line 78, in cac
he_download
    raise Exception("status code", r.status_code)
Exception: ('status code', 404)

**Comment by Duchongc** [comment]
我已经找到原因了，因为agent的版本问题，在git上没有0.5.1的版本，所以在下载的时候会提示404找不到

**Comment by codeskyblue** [comment]
0.5.1 tag 有点问题，所以直接删了
